#!/usr/bin/env bash
# This script takes command arguments and sends a file to the server
if [[ $# == 4 ]]
then
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
else
    echo Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
fi
#./0-transfer_file some_page.html 35.185.54.141 ubuntu /home/juansu/.ssh/holberton