#!/usr/bin/env bash
# This script installs nginx and changes the html file created by it.
sudo apt-get update -y
sudo apt-get install nginx -y
mystr="rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i "37i $mystr" /etc/nginx/sites-available/default
sudo service nginx restart
