#!/usr/bin/env bash
# This script pings the string passed as an argument 5 times.

var=("$@")
if [ -z "${var[0]}" ]
then
      echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
      ping -c 5 "$@"
fi
