#!/usr/bin/env bash
# This script runs nginx as nginx user
sudo chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill -f apache2
sudo -u nginx service nginx restart
